CREATE TABLE IF NOT EXISTS attendance_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    device_sn VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL DEFAULT '',
    card_name VARCHAR(128) NOT NULL DEFAULT '',
    card_no VARCHAR(64) NOT NULL DEFAULT '',
    method INT NOT NULL DEFAULT 0,
    direction VARCHAR(16) NOT NULL DEFAULT '',
    status INT NOT NULL DEFAULT 0,
    event_time DATETIME NOT NULL,
    create_time BIGINT NOT NULL DEFAULT 0,
    utc BIGINT NOT NULL DEFAULT 0,
    real_utc BIGINT NOT NULL DEFAULT 0,
    data_source VARCHAR(32) NOT NULL DEFAULT '',
    channel_index INT NOT NULL DEFAULT 0,
    door INT NOT NULL DEFAULT 0,
    reader_id VARCHAR(32) NOT NULL DEFAULT '',
    card_type INT NOT NULL DEFAULT 0,
    user_type INT NOT NULL DEFAULT 0,
    error_code INT NOT NULL DEFAULT 0,
    block_id BIGINT NOT NULL DEFAULT 0,
    image_count INT NOT NULL DEFAULT 0,
    raw_event JSON NULL,
    received_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_attendance_event_time (event_time),
    KEY idx_attendance_user_event_time (user_id, event_time),
    KEY idx_attendance_device_event_time (device_sn, event_time),
    KEY idx_attendance_block_id (block_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS door_status_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    device_sn VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    event_time DATETIME NOT NULL,
    utc BIGINT NOT NULL DEFAULT 0,
    real_utc BIGINT NOT NULL DEFAULT 0,
    data_source VARCHAR(32) NOT NULL DEFAULT '',
    channel_index INT NOT NULL DEFAULT 0,
    raw_event JSON NULL,
    received_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_door_status_event_time (event_time),
    KEY idx_door_status_device_event_time (device_sn, event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
